import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '../../..')
const release = readFileSync(join(repoRoot, '.github/workflows/release.yml'), 'utf8')
const smoke = readFileSync(join(repoRoot, '.github/workflows/runtime-sbom-smoke.yml'), 'utf8')
const verifier = readFileSync(join(repoRoot, 'scripts/verify-release-set.mjs'), 'utf8')
const generator = readFileSync(join(repoRoot, 'scripts/generate-runtime-sbom.mjs'), 'utf8')

describe('official-runtime SBOM release boundary', () => {
  it('uses one shared npm-native CycloneDX generator in release and PR smoke', () => {
    expect(generator).toContain("'sbom'")
    expect(generator).toContain("'--package-lock-only'")
    expect(generator).toContain("'--sbom-format'")
    expect(generator).toContain("'cyclonedx'")
    expect(generator).toContain("'--sbom-type'")
    expect(generator).toContain("'application'")
    expect(generator).toContain("root?.['bom-ref'] !== expectedRef")
    expect(generator).toContain("root?.purl !== expectedPurl")
    expect(generator).toContain("component?.name === '@deepseek-ai/dsh'")

    expect(release).toContain('node scripts/generate-runtime-sbom.mjs "$OUT"')
    expect(smoke).toContain('node scripts/generate-runtime-sbom.mjs "$OUT"')
  })

  it('makes the SBOM a required signed release dependency', () => {
    expect(release).toContain('  runtime-sbom:')
    expect(release).toContain('needs: [build-linux, build-windows, build-macos, runtime-sbom]')
    expect(release).toContain('needs: [build-linux, build-windows, build-macos, runtime-sbom, sign]')
    expect(release).toContain('dist-artifacts/*/*-official-runtime.cdx.json')
    expect(release).toContain('release-metadata/*-official-runtime.cdx.json.sha256')
  })

  it('requires verifier-level SBOM identity, checksum, and signature coverage', () => {
    expect(verifier).toContain("const METADATA_SUFFIXES = ['-official-runtime.cdx.json']")
    expect(verifier).toContain('expected exactly one official-runtime CycloneDX SBOM')
    expect(verifier).toContain("sbom?.bomFormat !== 'CycloneDX'")
    expect(verifier).toContain("root?.['bom-ref'] !== expectedRootRef")
    expect(verifier).toContain("root?.purl !== expectedRootPurl")
    expect(verifier).toContain("component?.name === '@deepseek-ai/dsh' && component?.version === officialPin")
    expect(verifier).toContain('missing sha256 sidecar for')
    expect(verifier).toContain('missing or empty sigstore bundle for')
  })

  it('keeps the SBOM smoke read-only and checksum-verifies generated bytes', () => {
    expect(smoke).toContain('permissions:\n  contents: read')
    expect(smoke).toContain('persist-credentials: false')
    expect(smoke).toContain('node scripts/checksum-release.mjs "$SBOM_PATH"')
    expect(smoke).toContain('sha256sum -c')
    expect(smoke).not.toContain('contents: write')
    expect(smoke).not.toContain('id-token: write')
  })
})
